# Generated by Django 4.1.4 on 2022-12-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
    ]
